version: '3.3'

services:
  nginx:
    image: nginx:latest
    container_name: todo-nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - todo-network

  db:
    build: ./postgres
    container_name: todo-db
    restart: unless-stopped
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: geheim
    networks:
      - todo-network

  app:
    build: .
    container_name: todo-app
    restart: unless-stopped
    command: "/app/TodoServer-exe /app/static"
    volumes:
      - data:/data
    environment:
      PORT: 8080
      PGUSER: postgres
      PGPASSWORD: geheim
      PGHOST: db
      DB_CONSTR: "dbname='Todos'"
    networks:
      - todo-network

volumes:
  data:

networks:
  todo-network: