version: '3.3'

services:
  nginx:
    image: nginx:latest
    container_name: todo-nginx
    restart: unless-stopped
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8070:80"
    networks:
      - todo-network
    depends_on:
      - app
      - db

  db:
    build: ./docker/postgres
    container_name: todo-db
    restart: unless-stopped
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: geheim
    networks:
      - todo-network

  app:
    build:
      context: .
      dockerfile: ./docker/app/dockerfile
    container_name: todo-app
    restart: unless-stopped
    command: "/app/TodoServer-exe /app/static"
    volumes:
      - data:/data
    environment:
      PORT: 8080
      PGUSER: postgres
      PGPASSWORD: geheim
      PGHOST: db
      DB_CONSTR: "dbname='Todos'"
    networks:
      - todo-network
    depends_on:
      - db

volumes:
  data:

networks:
  todo-network: